spring.application.name=gbk
app.jwt-secret=daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
app-jwt-expiration-milliseconds=604800000

# Datasource connection
spring.sql.init.mode=always
spring.sql.init.platform=mysql
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.hikari.maximumPoolSize=10   
spring.datasource.hikari.minimumIdle=5       
spring.datasource.hikari.idleTimeout=30000   
spring.datasource.hikari.maxLifetime=1800000
spring.datasource.hikari.connectionTimeout=30000 


# Hibernate
spring.jpa.hibernate.ddl-auto=create
spring.web.resources.add-mappings=false

# Database connection
spring.datasource.url=jdbc:mysql://202.10.35.65:3306/?allowPublicKeyRetrieval=true&useSSL=false
spring.datasource.username=gbk
spring.datasource.password=password

gbk.partner.id = 11983
gbk.partner.key = 53fdd7781054c10b94c1cbf63baaa74f

spring.cloud.compatibility-verifier.enabled=false
spring.jackson.deserialization.adjust-dates-to-context-time-zone=true
spring.jackson.time-zone=Asia/Jakarta


schedule.maintenance.Senin=125000000
schedule.maintenance.Selasa=125000000
schedule.maintenance.Rabu=125000000
schedule.maintenance.Kamis=125000000
schedule.maintenance.Jumat=125000000
schedule.maintenance.Sabtu=350000000
schedule.maintenance.Minggu=125000000


schedule.venuesf-of-unit-for-not-calculated.Akuatik[0]=Lahan Parkir Aquatic

schedule.price-for-venue-in-weekdays.Kolam\ Diving[0]=1200000
schedule.price-for-venue-in-weekdays.Kolam\ Diving[1]=1200000
schedule.price-for-venue-in-weekdays.Kolam\ Diving[2]=1200000
schedule.price-for-venue-in-weekend.Kolam\ Diving[0]=1400000
schedule.price-for-venue-in-weekend.Kolam\ Diving[1]=1400000
schedule.price-for-venue-in-weekend.Kolam\ Diving[2]=1400000

schedule.price-for-venue-in-weekdays.Kolam\ Tanding[0]=1400000
schedule.price-for-venue-in-weekdays.Kolam\ Tanding[1]=1400000
schedule.price-for-venue-in-weekdays.Kolam\ Tanding[2]=1400000
schedule.price-for-venue-in-weekend.Kolam\ Tanding[0]=2000000
schedule.price-for-venue-in-weekend.Kolam\ Tanding[1]=2000000
schedule.price-for-venue-in-weekend.Kolam\ Tanding[2]=2000000

schedule.price-for-venue-in-weekdays.Kolam\ Polo[0]=1000000
schedule.price-for-venue-in-weekdays.Kolam\ Polo[1]=1000000
schedule.price-for-venue-in-weekdays.Kolam\ Polo[2]=1000000
schedule.price-for-venue-in-weekend.Kolam\ Polo[0]=1500000
schedule.price-for-venue-in-weekend.Kolam\ Polo[1]=1500000
schedule.price-for-venue-in-weekend.Kolam\ Polo[2]=1500000

schedule.price-for-venue-in-weekdays.Kolam\ Pemanasan[0]=1100000
schedule.price-for-venue-in-weekdays.Kolam\ Pemanasan[1]=1100000
schedule.price-for-venue-in-weekdays.Kolam\ Pemanasan[2]=1100000
schedule.price-for-venue-in-weekend.Kolam\ Pemanasan[0]=1300000
schedule.price-for-venue-in-weekend.Kolam\ Pemanasan[1]=1300000
schedule.price-for-venue-in-weekend.Kolam\ Pemanasan[2]=1300000