name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to Server
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_KNOWN_HOSTS: ${{ secrets.SSH_KNOWN_HOSTS }}
        run: |
          echo "$SSH_PRIVATE_KEY" > private_key
          chmod 600 private_key
          scp -i private_key -o StrictHostKeyChecking=no target/SSec-0.0.1-SNAPSHOT.jar root@213.210.37.2:/opt/SSec-0.0.1-SNAPSHOT.jar
          ssh -i private_key -o StrictHostKeyChecking=no root@213.210.37.2 << 'EOF'
            chmod +x /opt/start_app.sh
            /opt/start_app.sh
          EOF
