name: CI/CD Pipeline

on:
  push:
    branches:
      - dev  # Change this to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: |
          mvn clean install -DskipTests

      - name: Verify build output
        run: |
          pwd
          ls -la target/

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 213.210.37.2
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          command_timeout: 500s
          script: |
            echo "Current working directory on server:"
            pwd
              
            cd BE-GBK
            mvn clean install
            cp -f target/SSec-0.0.1-SNAPSHOT.jar /opt
            echo "Listing files in /opt directory on server:"
            ls -la /opt
            echo "Setting execute permission and running the start script:"
            chmod +x /opt/start.sh
            cd /opt
            ./start.sh
            rm -rf /root/BE-GBK