name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Verify build output
        run: |
          pwd
          ls -la target/

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 213.210.37.2
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          command_timeout: 500s
          script: |
            echo "Current working directory on server:"
            pwd
            echo "Listing files in the current directory on server:"
            ls -la
            echo "Copying JAR file from GitHub Actions runner to /opt directory on server:"
            scp -o StrictHostKeyChecking=no -P 22 target/SSec-0.0.1-SNAPSHOT.jar ${{ secrets.SERVER_USERNAME }}@213.210.37.2:/opt/
            echo "Listing files in /opt directory on server:"
            ls -la /opt
            echo "Setting execute permission and running the start script:"
            chmod +x /opt/start_app.sh
            /opt/start_app.sh