name: CI/CD Pipeline

on:
  push:
    branches:
      - main  # Change this to your deployment branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
          cache: 'maven'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: 213.210.37.2
          username: ${{ secrets.SERVER_USERNAME }}
          password: ${{ secrets.SERVER_PASSWORD }}
          port: 22
          script: |
            cd /opt
            scp target/SSec-0.0.1-SNAPSHOT.jar ${{ secrets.SERVER_USERNAME }}@$213.210.37.2:/opt/SSec-0.0.1-SNAPSHOT.jar
            ssh ${{ secrets.SERVER_USERNAME }}@213.210.37.2 'chmod +x /opt/start_app.sh && /opt/start_app.sh'
